enum Lw006ParamAccess {
  readOnly,
  writeOnly,
  readWrite,
}

enum Lw006ParamKey {
  close(0x10, Lw006ParamAccess.writeOnly),
  reboot(0x11, Lw006ParamAccess.writeOnly),
  reset(0x12, Lw006ParamAccess.writeOnly),
  timeUtc(0x13, Lw006ParamAccess.writeOnly),
  timeZone(0x14, Lw006ParamAccess.readWrite),
  chipMac(0x15, Lw006ParamAccess.readOnly),
  selftestStatus(0x16, Lw006ParamAccess.readOnly),
  pcbaStatus(0x17, Lw006ParamAccess.readWrite),
  demandVersion(0x18, Lw006ParamAccess.readOnly),
  batteryPower(0x19, Lw006ParamAccess.readOnly),
  manufacturer(0x1A, Lw006ParamAccess.readWrite),
  deviceMode(0x1B, Lw006ParamAccess.readWrite),
  shutdownPayloadEnable(0x1C, Lw006ParamAccess.readWrite),
  offByButton(0x1D, Lw006ParamAccess.readWrite),
  lowPowerPayloadEnable(0x1E, Lw006ParamAccess.readWrite),
  lowPowerPercent(0x1F, Lw006ParamAccess.readWrite),
  heartbeatInterval(0x20, Lw006ParamAccess.readWrite),
  accWakeupCondition(0x21, Lw006ParamAccess.readWrite),
  accMotionCondition(0x22, Lw006ParamAccess.readWrite),
  buzzerSoundChoose(0x23, Lw006ParamAccess.readWrite),
  vibrationIntensity(0x24, Lw006ParamAccess.readWrite),
  motorState(0x25, Lw006ParamAccess.readOnly),
  resetMotorState(0x26, Lw006ParamAccess.writeOnly),
  indicatorStatus(0x27, Lw006ParamAccess.readWrite),
  batteryInfo(0x28, Lw006ParamAccess.readOnly),
  batteryReset(0x29, Lw006ParamAccess.writeOnly),
  lr1110Version(0x2A, Lw006ParamAccess.readOnly),
  autoPowerOnEnable(0x2B, Lw006ParamAccess.readWrite),
  hardwareVersion(0x2C, Lw006ParamAccess.readOnly),
  passwordVerifyEnable(0x30, Lw006ParamAccess.readWrite),
  password(0x31, Lw006ParamAccess.readWrite),
  advTimeout(0x32, Lw006ParamAccess.readWrite),
  advTxPower(0x33, Lw006ParamAccess.readWrite),
  advName(0x34, Lw006ParamAccess.readWrite),
  advInterval(0x35, Lw006ParamAccess.readWrite),
  standbyModePosStrategy(0x3F, Lw006ParamAccess.readWrite),
  periodicModePosStrategy(0x40, Lw006ParamAccess.readWrite),
  periodicModeReportInterval(0x41, Lw006ParamAccess.readWrite),
  timeModePosStrategy(0x42, Lw006ParamAccess.readWrite),
  timeModeReportTimePoint(0x43, Lw006ParamAccess.readWrite),
  motionModeEvent(0x44, Lw006ParamAccess.readWrite),
  motionModeStartNumber(0x45, Lw006ParamAccess.readWrite),
  motionModeStartPosStrategy(0x46, Lw006ParamAccess.readWrite),
  motionModeTripReportInterval(0x47, Lw006ParamAccess.readWrite),
  motionModeTripPosStrategy(0x48, Lw006ParamAccess.readWrite),
  motionModeEndTimeout(0x49, Lw006ParamAccess.readWrite),
  motionModeEndNumber(0x4A, Lw006ParamAccess.readWrite),
  motionModeEndReportInterval(0x4B, Lw006ParamAccess.readWrite),
  motionModeEndPosStrategy(0x4C, Lw006ParamAccess.readWrite),
  motionModeStationaryPosStrategy(0x4D, Lw006ParamAccess.readWrite),
  motionModeStationaryReportInterval(0x4E, Lw006ParamAccess.readWrite),
  filterBleScanPhy(0x50, Lw006ParamAccess.readWrite),
  filterRssi(0x51, Lw006ParamAccess.readWrite),
  filterRelationship(0x52, Lw006ParamAccess.readWrite),
  filterMacPrecise(0x53, Lw006ParamAccess.readWrite),
  filterMacReverse(0x54, Lw006ParamAccess.readWrite),
  filterMacRules(0x55, Lw006ParamAccess.readWrite),
  filterNamePrecise(0x56, Lw006ParamAccess.readWrite),
  filterNameReverse(0x57, Lw006ParamAccess.readWrite),
  filterNameRules(0x58, Lw006ParamAccess.readWrite),
  filterRawData(0x59, Lw006ParamAccess.readWrite),
  filterIbeaconEnable(0x5A, Lw006ParamAccess.readWrite),
  filterIbeaconMajorRange(0x5B, Lw006ParamAccess.readWrite),
  filterIbeaconMinorRange(0x5C, Lw006ParamAccess.readWrite),
  filterIbeaconUuid(0x5D, Lw006ParamAccess.readWrite),
  filterEddystoneUidEnable(0x5E, Lw006ParamAccess.readWrite),
  filterEddystoneUidNamespace(0x5F, Lw006ParamAccess.readWrite),
  filterEddystoneUidInstance(0x60, Lw006ParamAccess.readWrite),
  filterEddystoneUrlEnable(0x61, Lw006ParamAccess.readWrite),
  filterEddystoneUrl(0x62, Lw006ParamAccess.readWrite),
  filterEddystoneTlmEnable(0x63, Lw006ParamAccess.readWrite),
  filterEddystoneTlmVersion(0x64, Lw006ParamAccess.readWrite),
  filterBxpIbeaconEnable(0x65, Lw006ParamAccess.readWrite),
  filterBxpIbeaconMajorRange(0x66, Lw006ParamAccess.readWrite),
  filterBxpIbeaconMinorRange(0x67, Lw006ParamAccess.readWrite),
  filterBxpIbeaconUuid(0x68, Lw006ParamAccess.readWrite),
  filterBxpDevice(0x69, Lw006ParamAccess.readWrite),
  filterBxpAcc(0x6A, Lw006ParamAccess.readWrite),
  filterBxpTh(0x6B, Lw006ParamAccess.readWrite),
  filterBxpButtonEnable(0x6C, Lw006ParamAccess.readWrite),
  filterBxpButtonRules(0x6D, Lw006ParamAccess.readWrite),
  filterBxpTagEnable(0x6E, Lw006ParamAccess.readWrite),
  filterBxpTagPrecise(0x6F, Lw006ParamAccess.readWrite),
  filterBxpTagReverse(0x70, Lw006ParamAccess.readWrite),
  filterBxpTagRules(0x71, Lw006ParamAccess.readWrite),
  filterMkPirEnable(0x72, Lw006ParamAccess.readWrite),
  filterMkPirDetectionStatus(0x73, Lw006ParamAccess.readWrite),
  filterMkPirSensorSensitivity(0x74, Lw006ParamAccess.readWrite),
  filterMkPirDoorStatus(0x75, Lw006ParamAccess.readWrite),
  filterMkPirDelayResStatus(0x76, Lw006ParamAccess.readWrite),
  filterMkPirMajor(0x77, Lw006ParamAccess.readWrite),
  filterMkPirMinor(0x78, Lw006ParamAccess.readWrite),
  filterOtherEnable(0x79, Lw006ParamAccess.readWrite),
  filterOtherRelationship(0x7A, Lw006ParamAccess.readWrite),
  filterOtherRules(0x7B, Lw006ParamAccess.readWrite),
  wifiPosDataType(0x7D, Lw006ParamAccess.readWrite),
  wifiPosMechanism(0x7E, Lw006ParamAccess.readWrite),
  wifiPosTimeout(0x7F, Lw006ParamAccess.readWrite),
  wifiPosBssidNumber(0x80, Lw006ParamAccess.readWrite),
  blePosMechanism(0x81, Lw006ParamAccess.readWrite),
  blePosTimeout(0x82, Lw006ParamAccess.readWrite),
  blePosMacNumber(0x83, Lw006ParamAccess.readWrite),
  gpsModule(0x84, Lw006ParamAccess.readWrite),
  gpsExtremeModeL76C(0x85, Lw006ParamAccess.readWrite),
  gpsPosTimeoutL76C(0x86, Lw006ParamAccess.readWrite),
  gpsPdopLimitL76C(0x87, Lw006ParamAccess.readWrite),
  gpsPosDataType(0x88, Lw006ParamAccess.readWrite),
  gpsPosTimeout(0x89, Lw006ParamAccess.readWrite),
  gpsPosSatelliteThreshold(0x8A, Lw006ParamAccess.readWrite),
  gpsPosSystem(0x8B, Lw006ParamAccess.readWrite),
  gpsPosAutonomousAidingEnable(0x8C, Lw006ParamAccess.readWrite),
  gpsPosAuxiliaryLatLon(0x8D, Lw006ParamAccess.readWrite),
  gpsPosEphemerisNotifyEnable(0x8E, Lw006ParamAccess.readWrite),
  offlineLocationEnable(0x8F, Lw006ParamAccess.readWrite),
  loraNetworkStatus(0x90, Lw006ParamAccess.readOnly),
  loraRegion(0x91, Lw006ParamAccess.readWrite),
  loraMode(0x92, Lw006ParamAccess.readWrite),
  loraDevEui(0x93, Lw006ParamAccess.readWrite),
  loraAppEui(0x94, Lw006ParamAccess.readWrite),
  loraAppKey(0x95, Lw006ParamAccess.readWrite),
  loraDevAddr(0x96, Lw006ParamAccess.readWrite),
  loraAppSkey(0x97, Lw006ParamAccess.readWrite),
  loraNwkSkey(0x98, Lw006ParamAccess.readWrite),
  loraCh(0x99, Lw006ParamAccess.readWrite),
  loraDr(0x9A, Lw006ParamAccess.readWrite),
  loraUplinkStrategy(0x9B, Lw006ParamAccess.readWrite),
  loraDutycycle(0x9C, Lw006ParamAccess.readWrite),
  loraAdrAckLimit(0x9D, Lw006ParamAccess.readWrite),
  loraAdrAckDelay(0x9E, Lw006ParamAccess.readWrite),
  loraTimeSyncInterval(0x9F, Lw006ParamAccess.readWrite),
  loraNetworkCheckInterval(0xA0, Lw006ParamAccess.readWrite),
  deviceInfoPayload(0xA1, Lw006ParamAccess.readWrite),
  heartbeatPayload(0xA2, Lw006ParamAccess.readWrite),
  lowPowerPayload(0xA3, Lw006ParamAccess.readWrite),
  eventPayload(0xA4, Lw006ParamAccess.readWrite),
  gpsLimitPayload(0xA5, Lw006ParamAccess.readWrite),
  positioningPayload(0xA6, Lw006ParamAccess.readWrite),
  downLinkPosStrategy(0xB0, Lw006ParamAccess.readWrite),
  manDownDetectionEnable(0xB1, Lw006ParamAccess.readWrite),
  manDownPosStrategy(0xB2, Lw006ParamAccess.readWrite),
  manDownDetectionTimeout(0xB3, Lw006ParamAccess.readWrite),
  manDownDetectionReportInterval(0xB4, Lw006ParamAccess.readWrite),
  alarmType(0xB5, Lw006ParamAccess.readWrite),
  alarmExitTime(0xB6, Lw006ParamAccess.readWrite),
  alarmAlertTriggerType(0xB7, Lw006ParamAccess.readWrite),
  alarmAlertPosStrategy(0xB8, Lw006ParamAccess.readWrite),
  alarmAlertNotifyEnable(0xB9, Lw006ParamAccess.readWrite),
  alarmSosTriggerType(0xBA, Lw006ParamAccess.readWrite),
  alarmSosPosStrategy(0xBB, Lw006ParamAccess.readWrite),
  alarmSosReportInterval(0xBC, Lw006ParamAccess.readWrite),
  alarmSosNotifyEnable(0xBD, Lw006ParamAccess.readWrite),
  readStorageData(0xC0, Lw006ParamAccess.readWrite),
  clearStorageData(0xC1, Lw006ParamAccess.writeOnly),
  syncEnable(0xC2, Lw006ParamAccess.readWrite),
  outdoorBleReportInterval(0xD0, Lw006ParamAccess.readWrite),
  outdoorGpsReportInterval(0xD1, Lw006ParamAccess.readWrite),
  ;

  const Lw006ParamKey(this.key, this.access);

  final int key;
  final Lw006ParamAccess access;

  bool get canRead => access != Lw006ParamAccess.writeOnly;
  bool get canWrite => access != Lw006ParamAccess.readOnly;
}
